import type { View } from "./types";
export const views: View[] = [
  {
    id: "overview",
    title: "The whole picture.",
    subtitle: "Two levels. One home.",
    level: "All spaces",
    note: "Explore both floors side by side, or assemble the house in its source positions. The side-by-side view offsets the upper floor for inspection only.",
  },
  {
    id: "living",
    title: "Living & entry",
    subtitle: "Ground floor · Living space",
    level: "Ground floor",
    scene: "living-entry",
    interior: true,
    note: "The angled fireplace, two ceiling fans and patio opening follow the existing-condition model. Ceiling heights and finish details remain approximate.",
  },
  {
    id: "kitchen",
    title: "Kitchen",
    subtitle: "Ground floor · Kitchen",
    level: "Ground floor",
    scene: "kitchen",
    interior: true,
    note: "Existing navy cabinetry, pale countertops and appliance positions. Cabinet fronts and fittings are photograph-based approximations.",
  },
  {
    id: "powder",
    title: "Powder room",
    subtitle: "Ground floor · Under the stair",
    level: "Ground floor",
    scene: "powder",
    interior: true,
    note: "The separate under-stair powder room is retained. The handover plan records its provisional dimensions.",
  },
  {
    id: "garage",
    title: "Garage & utility",
    subtitle: "Ground floor · Garage",
    level: "Ground floor",
    eye: [90, 95, 62],
    target: [220, 187, 43],
    interior: true,
    note: "The garage washer, dryer and water heater are separate from the upstairs laundry. Framing and platform extents remain simplified.",
  },
  {
    id: "stairs",
    title: "Stairs & landing",
    subtitle: "Connecting the two levels",
    level: "Ground floor",
    scene: "stairs-nook",
    interior: true,
    note: "One straight flight connects the floors. Total rise, run and cross-floor registration remain provisional.",
  },
  {
    id: "bedroom1",
    title: "Primary bedroom",
    subtitle: "Upper floor · Bedroom 01",
    level: "Upper floor",
    scene: "bedroom-01",
    interior: true,
    note: "Existing window and room envelope from the V9.4 handover. The window-wall clear-width basis is 230 7/16 inches; overall registration remains provisional.",
  },
  {
    id: "bathroom1",
    title: "Primary bathroom",
    subtitle: "Upper floor · Bathroom 01",
    level: "Upper floor",
    scene: "master-bath-wet",
    interior: true,
    note: "Current shower and tub geometry retained. Unbuilt shower glass is excluded. Room depth, vanity height and the door-height chain need field confirmation.",
  },
  {
    id: "bedroom2",
    title: "Bedroom 02",
    subtitle: "Upper floor · Bedroom 02",
    level: "Upper floor",
    scene: "bedroom-02",
    interior: true,
    note: "The corrected closet return and window wall are retained. Doorway and return registration remain provisional.",
  },
  {
    id: "bathroom2",
    title: "Bathroom 02",
    subtitle: "Upper floor · Bathroom 02",
    level: "Upper floor",
    scene: "bathroom-02",
    interior: true,
    note: "This bathroom has its own layout. The shower-width reading and modeled opening still need reconciliation.",
  },
  {
    id: "hall",
    title: "Hall & storage",
    subtitle: "Upper floor · Hall recess",
    level: "Upper floor",
    eye: [191, 292, 167],
    target: [142, 292, 145],
    interior: true,
    note: "The open stepped recess is separate from the tall laundry door. The movable cabinet is omitted from this clean client view. Local recess dimensions are photo-derived; its absolute position is provisional.",
  },
  {
    id: "laundry",
    title: "Laundry closet",
    subtitle: "Upper floor · Stacked laundry",
    level: "Upper floor",
    scene: "Laundry",
    note: "A stacked washer/dryer closet faces the upstairs hall. This inspection view hides its door. Closet depth, setback and door height remain unresolved.",
  },
  {
    id: "patio",
    title: "Covered courtyard",
    subtitle: "Outside · Patio",
    level: "Outside",
    scene: "patio-covered",
    interior: true,
    note: "A closed courtyard with a four-post cover. No patio gate is modeled. Roof members, roof separation and paving limits are approximations.",
  },
];
